### ISSUE TITLE
Uncaught TypeError: this.$form is not a function

### ISSUE THREAD

**Issue by ServerJunge** [cretueusebiu/vform#1]
Hi,

first I want to say thank you for vform. I am using Laravel 5.3 and VueJS. I install vform via npm and in my bootstrap.js I have ('vform');

But I always get this error when I try to use a component with vform.

Uncaught TypeError: this.$form is not a function

**Comment by cretueusebiu** [comment]
You have to install it as a Vue plugin:

```
import VueForm from 'vform';

Vue.use(VueForm);
```

**Comment by ServerJunge** [comment]
`
window._ = require('lodash');

/**
 * We'll load jQuery and the Bootstrap jQuery plugin which provides support
 * for JavaScript based Bootstrap features such as modals and tabs. This
 * code may be modified to fit the specific needs of your application.
 */

window.$ = window.jQuery = require('jquery');
require('bootstrap-sass');

/**
 * Vue is a modern JavaScript library for building interactive web interfaces
 * using reactive data binding and reusable components. Vue's API is clean
 * and simple, leaving you to focus on building your next great project.
 */

window.Vue = require('vue');
require('vue-resource');
require('vform');

/**
 * We'll register a HTTP interceptor to attach the "CSRF" header to each of
 * the outgoing requests issued by this application. The CSRF middleware
 * included with Laravel will automatically verify the header's value.
 */

Vue.http.interceptors.push((request, next) => {
    request.headers['X-CSRF-TOKEN'] = Laravel.csrfToken;

    next();
});

/**
 * Echo exposes an expressive API for subscribing to channels and listening
 * for events that are broadcast by Laravel. Echo and event broadcasting
 * allows your team to easily build robust real-time web applications.
 */

// import Echo from "laravel-echo"

// window.Echo = new Echo({
//     broadcaster: 'pusher',
//     key: 'your-pusher-key'
// });
`

This is my laravel bootstrap. Vue-Resource works when i just require it

**Comment by cretueusebiu** [comment]
Replace ```require('vform');``` with:
```
var VueForm= require('vform');
Vue.use(VueForm);
```
