### ISSUE TITLE
How to use it without Nodejs

### ISSUE THREAD

**Issue by anardil** [cretueusebiu/vform#10]
Hello,

I use Vuejs without NodeJs.
How can I use vform?

Thanks.

**Comment by cretueusebiu** [comment]
The same way. It's just JavaScript.

**Comment by anardil** [comment]
Yes but you use:

```
import Vue from 'vue'
import { Form, HasError, AlertError } from 'vform'
```
That works only in NodeJs.
How can I do this without NodeJs?

Thanks.

**Comment by cretueusebiu** [comment]
My bad. 
Instead of using `import { Form, HasError, AlertError } from 'vform'` you can access the `vform` object from the global window. 

Example:
https://jsbin.com/kuyenobiwa/edit?html,js,console,output

**Comment by anardil** [comment]
Thank you. 👍
