### ISSUE TITLE
How upload image/file?

### ISSUE THREAD

**Issue by ahmadsafar** [cretueusebiu/vform#12]
i was using `FormData()` for file/image upload. but i dont know how to implement with this. please help me

**Comment by cretueusebiu** [comment]
Take a look at [this example](https://github.com/cretueusebiu/vform/blob/master/example/upload.html).

**Comment by Siphiwo** [comment]
Hi, I am using vForm and would like to upload multiple files on the <input type="file" multiple /> input field. I had a look at the example that @cretueusebiu provided but it is not a working solution for me. I am using FileReader() with the input fields.
