### ISSUE TITLE
v form version update error

### ISSUE THREAD

**Issue by ITApexGroup** [cretueusebiu/vform#123]
I use vform with cdn ( https://unpkg.com/vform ). It worked before 4 days ago. But, not working after latest version released.

Error example,
const { Form, HasError, AlertError } = window.vform;

The code is undefined error.
So, how to fix?

**Comment by cretueusebiu** [comment]
v2 doesn't include the Vue components anymore. 
You'll have to use a build system to use v2 with components.

If you still want to use the old version you can simply pin it to a specific version:
`https://unpkg.com/vform@1.0.1/dist/vform.umd.js`

**Comment by ITApexGroup** [comment]
Thanks
