### ISSUE TITLE
Bootstrap 4 components pointing to Bootstrap 5 components files on package.json exports field. 

### ISSUE THREAD

**Issue by joseareland** [cretueusebiu/vform#124]
Noticed that bug when updating to 2.0.3 version of your library on a B4 project. Looks like an easy fix.

**Comment by cretueusebiu** [comment]
It's like that because there was nothing different between them so I didn't duplicate some of the components.

**Comment by joseareland** [comment]
There are some little diferences on the dismissible alert button between them:

BS4: `<button type="button" class="close" data-dismiss="alert" aria-label="Close">
    <span aria-hidden="true">&times;</span>
  </button>`

BS5: <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>

**Comment by cretueusebiu** [comment]
But the only shared components are [Button](https://github.com/cretueusebiu/vform/blob/master/src/components/bootstrap5/Button.vue) and [HasError](https://github.com/cretueusebiu/vform/blob/master/src/components/bootstrap5/HasError.vue) which don't have that dismiss button.

**Comment by joseareland** [comment]
Understood and that is working just fine. It is all about the package exports in package.json in which you defined both bootstrap4 paths (./components/bootstrap4 and ./src/components/bootstrap4) pointing to bootstrap5 ones.


```
"./src/components/bootstrap4": "./src/components/bootstrap5/index.js",
"./components/bootstrap5": "./src/components/bootstrap5/index.js",
```

**Comment by cretueusebiu** [comment]
Oh I see. This is a mistake..

**Comment by cretueusebiu** [comment]
Fixed in the latest version.
