### ISSUE TITLE
customize 500 error response...

### ISSUE THREAD

**Issue by quyle92** [cretueusebiu/vform#125]
Hi there,
Is there any way where I can customize the response message for 500 Internal Server Error?
At the moment when sth goes wrong in the backend, it will show up laravel generated message, but I want it to display general message like "Sth went wrong with the system, please contact your admin".
How am I able to achieve that?
Thank you...

**Comment by nguyentranchung** [comment]
```ts
axios.interceptors.response.use(
  (response) => response,
  (error: AxiosError) => {
    const status = error?.response?.status || 0;

    if (status >= 500) {
      // handle
   }
  }
);
```
