### ISSUE TITLE
Original Data not reflected on parent component

### ISSUE THREAD

**Issue by rumeau** [cretueusebiu/vform#14]
Hello, im using vform on a custom component where im passing default data as a prop

Component 1
```
<template>
  <my-form :original-data="report">
     <template slot-scope="{form}">
       //... bunch of form fields
     </template>
   </my-form>
</template>
```

report is an object received as a prop from a parent component (AKA Component 0)

And my-form component defines form:

Component 2
```
data () {
    return {
      form: new Form(this.originalData)
    }
  }
```

My problem is that when I input some data on the form, the form objects reflects the value changed for the input modified, but the report object on the "Component 1" never gets the data modified.

How could i reflect the change on "Component 1" as i need to hide some fields there with a computed property based on the value of a property on the report object.

**Comment by cretueusebiu** [comment]
Once you pass the `report` object to the form via the `originalData` prop, the reference is lost. So changes made to the `form` instance won't reflect on the `report` object. You might want to emit a [custom event](https://vuejs.org/v2/guide/components.html#Custom-Events) back to the parent component.

**Comment by rumeau** [comment]
Thanks for replying. Is there any reason for loosing the reference? isn't that a feature of Javascript Objects.

I know i can make a custom event, but since i was using a vendor component i didnt want to touch it.

Thanks.

**Comment by cretueusebiu** [comment]
I think so you don't run into problems when you pass an existing object that you might change it and don't want to be changed in the form.

You can just add a watcher on the form in your component `this.$wach('form.some_field', () => {})` and emit the event.
