### ISSUE TITLE
Non-minimized version in NPM?

### ISSUE THREAD

**Issue by aphofstede** [cretueusebiu/vform#16]
I often explore my libs in-IDE, it would be handy if a not-minified file was distributed.
(The sourcemap doesn't get applied in IntelliJ/PHPStorm)

**Comment by cretueusebiu** [comment]
I think want you need, are the type definitions, like the official Vue packages have. But I use [vue build](https://github.com/vuejs/vue-cli/blob/master/docs/build.md) for the build process and it doesn't support that, only sourcemaps.
