### ISSUE TITLE
How to avoid ugly errors in console on form validation fails?

### ISSUE THREAD

**Issue by ilterocal** [cretueusebiu/vform#18]
Hi, i'm very new to Vue, and have simple question;

When laravel returns with 422, dev console shows the following error.

```
Uncaught (in promise) Error: Request failed with status code 422
    at createError (createError.js:16)
    at settle (settle.js:18)
    at XMLHttpRequest.handleLoad (xhr.js:77)
```
When we surround the await statement with a try catch, error goes away but form errors are not rendered. I want to suppress this error, and I also want to do something else when the form.post call fails. 

// Register the user.
const {data} = await this.form.post('/api/register');

Thanks for this work and for your help!

**Comment by cretueusebiu** [comment]
I'm testing with my [laravel-vue-spa](https://github.com/cretueusebiu/laravel-vue-spa) project and works fine:

```javascript
async login () {
  try {
    const { data } = await this.form.post('/api/login')

    console.log(data)
  } catch (e) {
    console.log(e)
  }
}
```

And the errors are rendered properly. 
Could you maybe post a repo with an example ?

**Comment by ilterocal** [comment]
Sorry that's my bad! 

laravel-vue-spa project register.vue page tries to login after register call. When I surround register with try catch and don't return in catch block, it call the login old errors from register gets cleared

`
      try {
        const { data } = await this.form.post('/api/register')
      console.log(data)
    } catch (e) {
      console.log(e)
      return; // <<<<<===== Solves the issue. 
    }
      // Log in the user.
      const { data: { token }} = await this.form.post('/api/login')
`
