### ISSUE TITLE
Loading data into form

### ISSUE THREAD

**Issue by Remo** [cretueusebiu/vform#19]
I've been looking for an example on loading data into a form, but haven't found anything. Looking at the code didn't really help, here's why.

Here's the PHP code:
```php
public function get()
{
    return response()->json(
        [
            'name' => 'My Customer',
            'email' => 'my@customer.tld',
        ]
    );
}
```

My first though was that I could simply call the `get` method and it would set `originalData`:
```javascript
this.form.get('/api/sales/customers/1')
```

But that doesn't seem to happen, the `get` method only returns the data.

I then try to find a way to set the data from outside the form class, but that didn't work either.

I could set the data by creating a new form object, but since I already had to create one to fetch the data that seems to be wrong. What am I missing?

**Comment by cretueusebiu** [comment]
You can just set them directly:

```javascript
const data = {}

Object.keys(data).forEach(key => {
  this.form[key] = data[key]
})
```

If you find yourself doing this often, you can add a new method to the `Form` class:

```javascript
import Form from 'vform'

Form.prototype.fill = function (data) {
  Object.keys(data).forEach(key => {
    this[key] = data[key]
  })
}
```

Then you can simply write:

```javascript
const data = {}

this.form.fill(data)
```

**Comment by Remo** [comment]
Thanks! Wouldn't it make sense to have that in the package by default? I find it very rare that you only want to save but not load data when working with a form.

**Comment by cretueusebiu** [comment]
Yes, I think I'll add.

**Comment by ByteRogue** [comment]
What is a solution for copying data from vuex state object? Currently inside component I watch computed property of that object and than fill form, when object changes. Is there any other solution, because as far as I know watchers for computed properties of store are not recommended?

**Comment by cretueusebiu** [comment]
@ByteRogue Can you post an example ?

**Comment by ByteRogue** [comment]
I will try to simplify my code and explain what is going on. On left side I have component with list of categories, and clicking on category change state of category active object in store, in a way it's dispatch action with load that object. On right side I have a component with a form with category attributes where I watch for category.active changes.
 
state.js
`
export default {
    category {
        active: null,
   }
}
`
mutations.js 
`
setCategoryActive(state, value) {
    state.category.active = value
}
`

getters.js
`
categoryActive : state => {
    return state.category.active
}
`

GeneralForm.vue
`
export default {
 ...
 computed : mapGetters['categoryActive']
 watch : {
    categoryActive(category) {
      if (category) {
        for (let key in category) {
          if (this.form.hasOwnProperty(key)) {
            this.form[key] = category[key]
          }   
        }   
      } else {
        this.form.clear();
        this.form.reset()
      }   
    }   
  }, 
}
`

**Comment by cretueusebiu** [comment]
You should use the store `watch` and `subscribe` methods: 
https://vuex.vuejs.org/en/api.html#vuexstore-instance-methods

**Comment by Nowi5** [comment]
Hi, I know that is a old topic, however, is there now a ready to go example / best practice?
Thank you.
