### ISSUE TITLE
validate a select field

### ISSUE THREAD

**Issue by NanoDev777** [cretueusebiu/vform#20]
I am validating the fields of a form and everything works very well, however I would like to know if it is possible to remove the error class to the select fields, this works well in a field of type text that is required, when writing this remover the error class, but in a select field that is required and I choose one of the options it keeps the error class, until I realize the submit. Is it possible to remove the error clause as soon as one of the options is selected ??

**Comment by cretueusebiu** [comment]
In my examples I only have `@keydown="form.onKeydown($event)"` that will clear the errors when you type something. 

For select inputs you need to add `@change="form.onKeydown($event)"` to the form.

Example: https://codepen.io/anon/pen/jYdpKp?editors=1010

**Comment by NanoDev777** [comment]
perfect that I was missing, thanks
