### ISSUE TITLE
Submit form with a submit button outside the form

### ISSUE THREAD

**Issue by jay7793** [cretueusebiu/vform#21]
Template code.

``` html
<form id="answerForm" @submit.prevent="createAnswer" @keydown="form.onKeydown($event)">
   <input type="text" name="title" v-model="form.content">
</form>

<v-button type="primary" @click.prevent="answerSubmit" class="btn-sm" :loading="form.busy">Submit</v-button>
```

I created answerSubmit() method inside Vue.js for submit form. But does not work.
``` javascript
answerSubmit () {
   document.getElementById('answerForm').submit()
},
```

PS. I'm using https://github.com/cretueusebiu/laravel-nuxt starter

**Comment by cretueusebiu** [comment]
Why don't you just call `createAnswer` when you click on the submit button ?

But if you really want to trigger the form use `dispatchEvent`:
https://codepen.io/anon/pen/PQqGVg
