### ISSUE TITLE
set error

### ISSUE THREAD

**Issue by alirezarazavi** [cretueusebiu/vform#22]
hi,
can i set error for input like this:
this.form.errors.username = "some error";

sometimes error don't come from server or errors is not validation error, like simple client form validation and i need to show errors with set error method but i don't know how.

thanx for the help.

**Comment by cretueusebiu** [comment]
Use:

```javascript
form.errors.set({
  username: 'Some error'
})
```
or, to merge with previous errors:
```javascript
form.errors.set({
  ...form.errors.errors,
  username: 'Some error'
})
```
