### ISSUE TITLE
Post function sends String [object Object]  instead of parameters when attaching a file

### ISSUE THREAD

**Issue by javiertoledos** [cretueusebiu/vform#23]
I'm using vforms 0.8.2 and axios 0.17. I'm new at vforms, but I ran into this issue. When you use vforms with a field being an array everything works fine, i.e.:

```javascript
new Form({ 
  description: 'some value',
  documentation: null,
  products: [ { code: "apple", price: 5 } , { code: "orange", price: 2.5 } ]
});
```

When doing a `this.form.post()` from a vue method, it works as expected by sending a json to the desired url. However when you attach a file to the form data, the sent data becomes multipart (obviously for handling the file) but any array/object field (in this case products) is sent as a string "[object Object]":

The request payload sent is this one: 
```
------WebKitFormBoundarykcEGETElI1QRyPXB
Content-Disposition: form-data; name="documentation"; filename="test.zip"
Content-Type: application/x-zip-compressed

------WebKitFormBoundarykcEGETElI1QRyPXB
Content-Disposition: form-data; name="products"

[object Object]
------WebKitFormBoundarykcEGETElI1QRyPXB--
``` 

Instead of this:
```
------WebKitFormBoundaryxew11gK9NAMhdxsN
Content-Disposition: form-data; name="documentation"; filename="test.zip"
Content-Type: application/x-zip-compressed

------WebKitFormBoundaryxew11gK9NAMhdxsN
Content-Disposition: form-data; name="products[0][code]"

apple
------WebKitFormBoundaryxew11gK9NAMhdxsN
Content-Disposition: form-data; name="products[0][price]"

5
------WebKitFormBoundaryxew11gK9NAMhdxsN
Content-Disposition: form-data; name="products[1][code]"

orange
------WebKitFormBoundaryxew11gK9NAMhdxsN
Content-Disposition: form-data; name="products[1][price]"

2.5
------WebKitFormBoundaryxew11gK9NAMhdxsN--
```

Unfortunately, this is my first time with vue, and node.js in general so i'm not sure how I can implement the fix, but the solution is to make sure that object parameters are properly encoded when the post request is a `multipart/form-data`. I researched that flat module could flatten an object but it doesn't adhere to php notation of using brackets for array parameters.

**Comment by cretueusebiu** [comment]
Check out [this example](https://github.com/cretueusebiu/vform/blob/master/example/upload.html).
Now you just have to pass the `transformRequest` to axios where you can transform the data however you want.

**Comment by javiertoledos** [comment]
Very useful thanks! I will try v1.0.0 and use your example.
