### ISSUE TITLE
Issue on select and textarea

### ISSUE THREAD

**Issue by raphcadiz** [cretueusebiu/vform#26]
error message is not working for input type select and textarea

```
<div class="col-md-7">
              <select v-model="form.category_id" name="category_id" class="form-control">
                <option v-for="category in company_categories" v-bind:value="category.id">{{category.name}}</option>
              </select>
            <has-error :form="form" field="category_id"/>
          </div>
```
```
<div class="col-md-7">
            <textarea v-model="form.description" class="form-control" name="description" rows="4"></textarea>
            <has-error :form="form" field="description"/>
          </div>
```

Laravel has error response with this keys but it does not work if input types are select and textarea. haven't tested on other input types yet, it only work on text type for me.

**Comment by cretueusebiu** [comment]
Everything works fine.. https://codepen.io/anon/pen/MQMrQW?editors=1010

Your html is all wrong.. please see the included Bootstrap examples.
