### ISSUE TITLE
implement vform in vuetify

### ISSUE THREAD

**Issue by NanoDev777** [cretueusebiu/vform#27]
I really like this library and I have been using it, I have a doubt since I am not an expert, it is possible to use it without boostrap ?, right now I am using vuetify and I would like to use vform, this is possible or has some problems. I hope I remove the doubt ..

**Comment by cretueusebiu** [comment]
Of course you can. Bootstrap is only used for the default components. 

You'll just have to write the [components](https://github.com/cretueusebiu/vform/tree/master/src/components) with Vuetify.

Or just use [plain html](https://github.com/cretueusebiu/vform/blob/master/example/basic.html) with classes when displaying the errors.
