### ISSUE TITLE
Disable form button until server response

### ISSUE THREAD

**Issue by koekaverna** [cretueusebiu/vform#28]
Is there any way to disable sending form again until server response ?

**Comment by cretueusebiu** [comment]
Yes, use `form.busy`

```vue
<button :disabled="form.busy" type="submit" class="btn btn-primary">
  Log In
</button>
```

**Comment by cretueusebiu** [comment]
Check out this button component that integrates with vform"

[Button.vue](https://github.com/cretueusebiu/laravel-vue-spa/blob/master/resources/assets/js/components/Button.vue) + [buttons.scss](https://github.com/cretueusebiu/laravel-vue-spa/blob/master/resources/assets/sass/elements/_buttons.scss)
