### ISSUE TITLE
Validation errors

### ISSUE THREAD

**Issue by kwame101** [cretueusebiu/vform#29]
Hi ,

I want to validate an array of objects but when I do the error feedback doesn't get sent back to the form field. Example I have simple form like 

```
details : {
         id: ' ',
         name: ' '
}
```
And I'm using laravel to validate the request but when it returns the error say **details.name is field is required** feedback is not shown on field nor error displayed. Basically what I want to do is something simple like triggering the main field to display an error like **details field required**.  I'm not sure if this can be handled in the laravel itself or by tweaking the form to react to this situation. Thanks in advance

**Comment by cretueusebiu** [comment]
Please post a reproduction component with the form the the controller with validation rules so I can test it.

**Comment by kwame101** [comment]
Thanks for you help i figured it out, the problem was with my validation checks in laravel. This can be closed
