### ISSUE TITLE
Custom axios (from Nuxt)

### ISSUE THREAD

**Issue by Iworb** [cretueusebiu/vform#30]
I want to use @nuxtjs/axios with my own handlers. Is there a way to use this axios instance instead of default one?

**Comment by cretueusebiu** [comment]
Not yet, but it's something I'm planing to implement soon.

**Comment by Iworb** [comment]
Okay. I'll be waiting for this feature.

**Comment by cretueusebiu** [comment]
What you can do in the meantime, is to override the `submit` method on the `Form` class and use your axios instance:

```javascript
import Form from 'vform'

Form.prototype.submit = function (method, url, config = {}) {
  // https://github.com/cretueusebiu/vform/blob/master/src/Form.js#L146
 
  myAxiosInstance.request(...)
}
```

**Comment by drewjbartlett** [comment]
If you allow injection of your http instance that would be a simple fix as well :)

**Comment by drewjbartlett** [comment]
FYI for those looking to do this in nuxt:

`plugins/vform.js`

```js
import Form from 'vform';

export default ({ app }, inject) => {
  Form.prototype.submit = function submit(method, url, config = {}) {
    this.startProcessing();

    const data = method === 'get'
      ? { params: this.data() }
      : this.data();

    return new Promise((resolve, reject) => {
      app.$axios.request({
        url: this.route(url), method, data, ...config,
      })
        .then(response => {
          this.finishProcessing();

          resolve(response);
        })
        .catch(error => {
          this.busy = false;

          if (error.response) {
            this.errors.set(this.extractErrors(error.response));
          }

          reject(error);
        });
    });
  };

  app.$vform = (...params) => new Form(...params);
  inject('vform', (...params) => new Form(...params));
};
```

`nuxt.config.js`

`plugins: [... '~/plugins/vform.js'],`

and in your Vue components:

```js
...

data() {
   return {
      form: this.$vform(...),
   }
}
```

**Comment by WilliamBlais** [comment]
I constantly get Cannot read property '$vform' of undefined while using the solution above. Did it change with new nuxt versions? @drewjbartlett

**Comment by skashfykv** [comment]
No. This still gives this.$vform is not a function.

**Comment by BenceSzalai** [comment]
Meanwhile apparently since v1.0.1 (2019-06-01, 782c7108ed2716503d4ae56c6150e11dba94e017) it is now much simpler to set up custom Axios instance.
`Form.axios = customAxiosInstance`

This means the above given example `plugins/vform.js` can be simplified. For example if you are using `@nuxtjs/axios` as a module in nuxt, to use the same Axios it may look like this:
```
import Vue from 'vue'
import { default as Form, HasError, AlertError, AlertSuccess } from 'vform'

Vue.component(HasError.name, HasError)
Vue.component(AlertError.name, AlertError)
Vue.component(AlertSuccess.name, AlertSuccess)

export default ({ $axios }) => {
    Form.axios = $axios
}
```

Also this way it can be used on components just as usual:
```
data () {
  return {
    form: new Form({...})
  }
},
```

**Comment by teguhsangra** [comment]
can i use this.$vform.fill(data) for autofill ?
if i use plugins/vform.js
