### ISSUE TITLE
Form inside v-for

### ISSUE THREAD

**Issue by maganius** [cretueusebiu/vform#31]
Hello @cretueusebiu,

im very new on vuejs and im trying learn this awesome framework..

I have a simple question.

How I can implement this vform inside a v-for?

Here's an example:

https://shrib.com/#TIbHYwTTLsxgtll0Pw.b
I can't put the code in this editor, i dont know why.

what's the correct way to implement this? because when I send the form, the form send again all data not the form where I trigger the submit.

If i put this on a separate component this work as expected but its correct? I need put the forms in separate component if is inside in a v-for? its some crazy for my brain!, imagine if you have 5 or 6 forms! it would 5 or 6 components?

**Comment by cretueusebiu** [comment]
You either set up the fields in the constructor or use [Vue.set](https://vuejs.org/v2/api/#Vue-set) to set the props dynamically on the form. 

```javascript
['a', 'b', 'c'].forEach(prop => {
  this.$set(this.form, prop, '')
})
```
