### ISSUE TITLE
How can I apply another CSS Framework?

### ISSUE THREAD

**Issue by samuelterra22** [cretueusebiu/vform#33]
I want to use the package, but in my project I do not use Bootstrap. Currently using Bulma. Is there any simple way to use the css framework without having to modify dependency?

**Comment by samuelterra22** [comment]
One solution was to rewrite the HasError, AlertError, and AlertSuccess components inside the project components folder.

**Comment by cretueusebiu** [comment]
The included components are for Bootstrap, but you can use it with anything as long as you write your own components.
