### ISSUE TITLE
errors not displayed on return with error 422

### ISSUE THREAD

**Issue by joelpiccoli** [cretueusebiu/vform#34]
I'm getting a 422 error while getting the return from a Laravel's Form Request Validation class, but the <has-error> component are not being displayed...

```
POST http://project.build/save-account 422 (Unprocessable Entity)

register.js?id=51eaeeff0b3abd47a38c:5169 Uncaught (in promise) Error: Request failed with status code 422
    at createError (register.js?id=51eaeeff0b3abd47a38c:5169)
    at settle (register.js?id=51eaeeff0b3abd47a38c:5320)
    at XMLHttpRequest.handleLoad (register.js?id=51eaeeff0b3abd47a38c:4730)
```
What I can do to solve this problem???

**Comment by cretueusebiu** [comment]
Please post a reproduction link.

**Comment by Flow999Cloud** [comment]
@joelpiccoli  Did you find the solution?

**Comment by rifton007** [comment]
Same problem, do you have a fix ?

**Comment by koekaverna** [comment]
Same issue.
Show error page "Request failed with status code 422" on dev mode
But works fine in production

"nuxt": "2.4.3",
"axios": "0.18.0",

**Comment by Zooba21** [comment]
It's making a long time but I faced the problem today and I noticed that to show up the input related to the error must have the " is-invalid " class. Just to those who are in trouble ;)

**Comment by Sweeeeep** [comment]
just comment this line
![image](https://user-images.githubusercontent.com/13380637/61316571-db722480-a833-11e9-9495-a3dd1ae0d689.png)
