### ISSUE TITLE
Can it work with Nuxt.js Axios Module ?

### ISSUE THREAD

**Issue by jay7793** [cretueusebiu/vform#36]
I want to use vform with Nuxt.js Axios Module using the code below. But it does not work properly. It does not send any requests to the server. Previously, I had used the normal axios plugin, it could work properly.

```javascript
async create({ commit }, params = {}) {
    commit('CREATING')
    try {
      const { data } = await params.form.post(`questions/${params.question}/answer`)
      commit('CREATE_SUCCESS', data)
    } catch (e) {
      commit('CREATE_FAILURE', e.message)
    }
 },
```

The axios module. using this format 

```javascript
async create({ commit }, params = {}) {
    commit('CREATING')
    try {
      const { data } = await this.$axios.$post(`questions/${params.question}/answer`)
      commit('CREATE_SUCCESS', data)
    } catch (e) {
      commit('CREATE_FAILURE', e.message)
    }
  },
```

Is possible to be able to use form with Nuxt.js Axios Module ?
Thank you for suggestion

**Comment by cretueusebiu** [comment]
Yes, but you'll have to use [this trick](https://github.com/cretueusebiu/vform/issues/30) for using a custom axios instance.

**Comment by jay7793** [comment]
Sorry. I don't know how to use with vuex
Can you show a bit example how to use in vuex store by using from my code above ?

Thank

**Comment by cretueusebiu** [comment]
Just pass the form object to the action and make the request there.

```javascript
this.$store.dispatch('login', this.form)
```

```javascript
async login ({ commit}, form) {
  const { data } = await form.post('/login')
  
  commit('SOME_MUTATION', data)
}
```
