### ISSUE TITLE
Scroll to the first input field and focus when validation fail

### ISSUE THREAD

**Issue by jay7793** [cretueusebiu/vform#37]
I have a long form with submit button at the bottom of the form. I have multiple input fields in the form marked required from sever side. So when one of the few input fields at the top of the form are left blank and I scroll down to click submit, the error message came out below each input field However, I have to scroll up all the way to the top to enter the input. How can I make it automatically scroll up to focus on the first input error?

I really appreciate it.

**Comment by cretueusebiu** [comment]
After you submitted the form use `form.errors` to access the errors and then scroll down to the first input associated with the first error.
