### ISSUE TITLE
Can't upload file to server

### ISSUE THREAD

**Issue by jay7793** [cretueusebiu/vform#38]
Hello
I'm having trouble uploading form file to server. I follow this [example](https://github.com/cretueusebiu/vform/blob/master/example/upload.html). I do not know what's wrong with my code. Please help.

This is my code for post to server (When clicked Submit button)
``` javascript
update() {
   this.form
   .post('/settings/profile', {
      // Transform form data to FormData
      transformRequest: [
        function(data) {
          return objectToFormData(data)
        }
      ]
    })
   .then(({ data }) => {
     this.$store.dispatch('auth/updateProfile', { data })
   })
}
```

Before upload to server I monitor the form object using console.log() the avatar field contain file data.

![image](https://user-images.githubusercontent.com/11994458/41772227-f2a0ed8c-7641-11e8-9fd5-3e4a9c1336fa.png)

Then upload the file to the server, each field works correctly except for the avatar field (it is empty).

![image](https://user-images.githubusercontent.com/11994458/41772094-7ef0de88-7641-11e8-98a9-bf64bfaba791.png)

I don't understand where the data is missing

Thank you.

**Comment by christiancazu** [comment]
> Try with this.form.submit not this.form.post

i can't do it work with put or patch, when i send the request arrives empty to my backend

**Comment by jimohalloran** [comment]
Same issue here.  Using `form.submit` instead of `form.post` works fine for me.  But if I try this with `form.submit('patch'` my backend doesn't receive the form data.

**Comment by cretueusebiu** [comment]
See my comment https://github.com/cretueusebiu/vform/issues/54#issuecomment-463105363
