### ISSUE TITLE
422 (Unprocessable Entity)

### ISSUE THREAD

**Issue by Hujjat** [cretueusebiu/vform#40]
Thanks for the great package firstly. 

I still have the issue of showing 422 error in console after validation fails. 

Here is my code. 

`

    methods:{

        async addMember(){
            try {
                await this.form.post('/api/user')
                this.form.reset()
                alert("User Created")
            } catch (e) {
                // console.log(e)
              }
        }
    }

`

When validation fails, it should give the error in console. How can I avoid the error. 

Thanks.

**Comment by cretueusebiu** [comment]
You mean an error like this ? 

![screenshot_2](https://user-images.githubusercontent.com/1517945/43469701-73fbe6e0-94ef-11e8-836c-c89141696f09.png)

You can't suppress that even with a try/catch.

**Comment by Hujjat** [comment]
So, How can we prevent showing that error please ? 

Thanks

**Comment by cretueusebiu** [comment]
You can't. That's how the browser shows it.

**Comment by Hujjat** [comment]
alright, Thanks :)

**Comment by shahajahancse** [comment]
but, have not any solution ?
