### ISSUE TITLE
Support vue-i18n

### ISSUE THREAD

**Issue by ZapevalovAnton** [cretueusebiu/vform#44]
Do you have plans for support vue-i18n?

**Comment by cretueusebiu** [comment]
The error messages are generated by the backend, the Laravel validator. So you would translate the strings from Laravel.

**Comment by ZapevalovAnton** [comment]
If i want translate strings from frontend with vue-i18n?

**Comment by dz0wkn** [comment]
![loading4](https://user-images.githubusercontent.com/20279180/58866575-4d523c80-86d2-11e9-9ecf-f223f41276dc.gif)

**Comment by cretueusebiu** [comment]
This package is meant to be used with the Laravel validator and translator.
