### ISSUE TITLE
When form values are objects and the objects are null it thrown an exception when fill

### ISSUE THREAD

**Issue by alfonsobries** [cretueusebiu/vform#46]
So I have this form and I get an user to populate the form:

```
form: new Form({
        name: null,
        email: null,
        address: {
          country: 'MX',
          state: null,
          city: null,
          suburb: null,
          zip: null,
          number: null,
          interior_number: null,
          street: null
        },
      }),
```
```
this.form.fill(user)
```
Everything ok but sometimes the `user.address` is null, in that cases when I call the `fill` method  seems like the address object is setted to null and not the full object, so in the v-model (for example form.address.street) throws an exception `Cannot read property 'state' of null`

MThe fill method should `fill` the form as constructed don't you think?  or maybe create a method like `fillStrict` or something?

**Comment by alfonsobries** [comment]
btw I can help with a PR to add method like `fillStrict` but what do you think?

**Comment by cretueusebiu** [comment]
I guess we can change this one since this should be the default behavior. But how deep do we go into the form object ?

**Comment by alfonsobries** [comment]
I think that just go to one attribute deep will be enough for most of the cases or maybe create some kind of recursive assignation?

**Comment by bernardonigbinde** [comment]
Any word on the progress of this issue yet?

**Comment by bernardonigbinde** [comment]
Here's what I've done in the mean time. Perhaps this helps you:

```
for (var property in user) {
	if (user.hasOwnProperty(property)) {
		if (user[property] == undefined) {
			user[property] = this.form.originalData[property];
		}
	}
}
```

Not sure if that's the best solution, but it appears to be working so far.

I do get this warning though:
`Comparison user[property] == undefined may cause unexpected type coercion`
