### ISSUE TITLE
Error: [vuex] Do not mutate vuex store state outside mutation handlers.

### ISSUE THREAD

**Issue by dipesh112** [cretueusebiu/vform#48]
vuex state
`const state ={

   form: new Form({

            id:null,
            fullname: null,
            username: null,
            email: null,
            password: null,
            role:null
        }),
}`
vuex action

`
const action ={

    storeData({commit,state}){
        commit('LOADING');
        return new Promise((resolve, reject)=>{
            let params = _.cloneDeep(state.form)

            axios.post(APP_CONFIG.API_URL+'/users',params)
            .then(response =>{
                commit('RESET_STATE')
                resolve();
            })
            .catch(error =>{
                //commit('ERROR',error)
                //reject(error)
            });
        });
    },
}`

**Comment by esbolice** [comment]
Hi, what was the reason for closing the issue? have you found a way?
