### ISSUE TITLE
npm ERR! A complete log of this run can be found in:

### ISSUE THREAD

**Issue by IsoftTech** [cretueusebiu/vform#49]
Hello everyone here. am working on laravel & Vuejs project, it was working fine but suddenly developed a problem. The error started when i was installing vform. I've tried many solutions online but still not working. Your help is highly appreciated. here's the error:
npm ERR! This is an error with npm itself. Please report this error at:
npm ERR!     <https://npm.community>

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Isoft\AppData\Roaming\npm-cache\_logs\2018-12-28T01_28_24_979Z-debug.log

**Comment by v-radev** [comment]
Can you give more info how this happens? Is it when you run `npm install`? Perhaps some part of the **2018-12-28T01_28_24_979Z-debug.log** file would be useful?

**Comment by IsoftTech** [comment]
npm install, update was working fine. but when i tried to install the package it was giving some errors so i checked online on how to solve it, i followed their steps unfortunately i ran into this error. Now if run npm install, npm update and npm i axios vform it bring out this error:
 npm i axios vform
npm ERR! error:0906D06C:PEM routines:PEM_read_bio:no start line
npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Isoft\AppData\Roaming\npm-cache\_logs\2018-12-28T10_53_14_079Z-debug.log

**Comment by IsoftTech** [comment]
My nodejs is v10.15.0 and npm is v6.4.1

**Comment by IsoftTech** [comment]
Here's the new error:
:\Users\Isoft\Desktop>npm config set registry http://registry.npmjs.org

C:\Users\Isoft\Desktop>npm install
npm WARN saveError ENOENT: no such file or directory, open 'C:\Users\Isoft\Desktop\package.json'
npm WARN enoent ENOENT: no such file or directory, open 'C:\Users\Isoft\Desktop\package.json'
npm WARN Desktop No description
npm WARN Desktop No repository field.
npm WARN Desktop No README data
npm WARN Desktop No license field.

up to date in 10.672s

**Comment by IsoftTech** [comment]
After install, it in my project directory and got this:
 npm config set registry http://registry.npmjs.org
PS C:\xampp\htdocs\applications\isofttechn> npm install
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@^1.2.2 (node_modules\chokidar\node_modules\fsevents):
npm WARN network SKIPPING OPTIONAL DEPENDENCY: request to http://registry.npmjs.org/fsevents failed, reason: getaddrinfo ENOTFOUND registry.npmjs.org registry.npmjs.org:80

up to date in 32.859s

**Comment by v-radev** [comment]
That should be ok, I think fsevents has some problems depending on the OS. If you get green at the end and just warnings you should be good.

**Comment by IsoftTech** [comment]
Ok, here is the link to my repo please check it for me
https://github.com/IsoftTech/IsofttechStarterAdmin.git
Username: admin@me.com
Password is password

**Comment by IsoftTech** [comment]
Here's the error:
npm install
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@^1.2.2 (node_modules\chokidar\node_modules\fsevents):
npm WARN network SKIPPING OPTIONAL DEPENDENCY: request to http://registry.npmjs.org/fsevents failed, reason: getaddrinfo ENOTFOUND registry.npmjs.org registry.npmjs.org:80

up to date in 48.498s

**Comment by IsoftTech** [comment]
I've not tried it, I'll try and give you feedback.
I thanks very much, I appreciate your effort.

**Comment by IsoftTech** [comment]
Hello sir, I feel like hugging you now. It's works find now, I really appreciate. If I have enough money now i would have appreciated you for you effort. You'll such a great man, thanks.

npm i axios vform
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.4 (node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.4: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})

+ axios@0.18.0
+ vform@1.0.0
added 1 package from 1 contributor, updated 1 package and audited 15928 packages in 66.454s
found 0 vulnerabilities

PS C:\xampp\htdocs\applications\isofttechn>

**Comment by IsoftTech** [comment]
The problem was with the npm registry. I solve the issue by simply running this command.
[](  npm config set registry http://registry.npmjs.org )or
 [](npm set registry http://registry.npmjs.org/)
 and then do the install again. This works for me and I sure hope it works for you.

**Comment by v-radev** [comment]
Awesome, happy I could help.

**Comment by cheetaof71** [comment]
> 
> 
> npm install, update was working fine. but when i tried to install the package it was giving some errors so i checked online on how to solve it, i followed their steps unfortunately i ran into this error. Now if run npm install, npm update and npm i axios vform it bring out this error:
> npm i axios vform
> npm ERR! error:0906D06C:PEM routines:PEM_read_bio:no start line
> npm ERR! A complete log of this run can be found in:
> npm ERR! C:\Users\Isoft\AppData\Roaming\npm-cache_logs\2018-12-28T10_53_14_079Z-debug.log



> 
> 
> The problem was with the npm registry. I solve the issue by simply running this command.
> []( npm config set registry http://registry.npmjs.org )or
> [](npm set registry http://registry.npmjs.org/)
> and then do the install again. This works for me and I sure hope it works for you.

Yes I also faced this error and solved it by on this away.

**Comment by Adityarauthan2409** [comment]
No this thing is not working for me

**Comment by Mateusnasciment** [comment]
PS C:\Users\cce> npm install -g yarn
npm ERR! Unexpected token '.'

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\cce\AppData\Local\npm-cache\_logs\2023-11-20T22_32_37_728Z-debug-0.log
PS C:\Users\cce>
