### ISSUE TITLE
work with photos

### ISSUE THREAD

**Issue by bazuzu931** [cretueusebiu/vform#50]
can you add fields for images?

**Comment by cretueusebiu** [comment]
If you want to upload files use the [upload example](https://github.com/cretueusebiu/vform/blob/master/example/upload.html).

**Comment by bazuzu931** [comment]
how about multifiles?

**Comment by bazuzu931** [comment]
> If you want to upload files use the [upload example](https://github.com/cretueusebiu/vform/blob/master/example/upload.html).

how about multifiles?
