### ISSUE TITLE
How to upload Image in Vform

### ISSUE THREAD

**Issue by blpraveen** [cretueusebiu/vform#52]
I have other fields with the  vform. So how do I upload the image
                     
                     <div class="form-group">
                        <select v-model="form.category_id" id="category" name="category" 
                            
                            class="form-control" :class="{ 'is-invalid': form.errors.has('category') }">
							<option v-for="category in categories.data"  :value="category.id" v-bind:selected="category.id != null">{{category.name}}</option>
						</select>
                        <has-error :form="form" field="category"></has-error>
                    </div>
 
                     <div class="form-group">
                        <input v-model="form.featured" id="featured" type="file" name="featured"
                            placeholder="Featured Image" @change="selectFile"
                            class="form-control" :class="{ 'is-invalid': form.errors.has('featured') }">
                        <has-error :form="form" field="featured"></has-error>
                    </div>

**Comment by cretueusebiu** [comment]
If you want to upload files use the [upload example](https://github.com/cretueusebiu/vform/blob/master/example/upload.html).

**Comment by blpraveen** [comment]
Is there an example to upload Image with other form input elements not just only the file input

**Comment by Xoshbin** [comment]
@cretueusebiu This example only works for creating new data in database, what about editing a data that's already been saved. right now I'm working on something similar but it's not sending the data to the controller, it's all null. That's my code:
```
updateSupplier() {
      this.form
        .submit("put", "/api/suppliers/" + this.form.id, {
          // Transform form data to FormData
          transformRequest: [
            function(data, headers) {
              return objectToFormData(data);
            }
          ],

          onUploadProgress: e => {
            // Do whatever you want with the progress event
             console.log(e)
          }
        })
        .then(({ data }) => {
          
        });
    }
```
