### ISSUE TITLE
how to do with vform post with header multipart/form-data

### ISSUE THREAD

**Issue by shiroamada** [cretueusebiu/vform#54]
how to do with vform post with header multipart/form-data?
I saw your example is when select input file it do ajax file upload. 
But for my case, I need to submit together with other form data. I am upload an excel file
Is there any way In your this.form.post(), to add the header info?

**Comment by cretueusebiu** [comment]
With [this example](https://github.com/cretueusebiu/vform/blob/master/example/upload.html) you can upload files and still pass along other fields.

**Comment by shiroamada** [comment]
Do you mind show me the example? Ya, I read your example upload, how do you send header?
```
{headers: {
        'Content-Type': 'multipart/form-data'
}}
```


```

          this.form.submit('post', '/upload', {
              // Transform form data to FormData
              transformRequest: [function (data, headers) {
                return objectToFormData(data)
              }],
```

**Comment by shiroamada** [comment]
Ok, I found what out what is the issue.
I didn't notice, you imported extra library call 'objectToFormData.js', that why I can't convert my file object. When I post to the URL. It keep showing empty. 

My first thought is the header problem, and end up it is the key point **objectToFormData**. Once I imported to my script it work like charm.

Thanks!

For those who want to change the headers would be like below. But for case, the library will change according. If you change manually it will break the code.

```
this.form.submit('post', '/upload', {
              //change custom header, for my case, it does not need it, if you add it. You break the code.
              headers: { 'content-type': 'multipart/form-data' },
              // Transform form data to FormData
              transformRequest: [function (data, headers) {
                return objectToFormData(data)
              }],
```

**Comment by mohdabbas** [comment]
Is this working with this.form.submit('put'....? Working perfectly with post, but not with Put! return objectToFormData(data) return null!

**Comment by cretueusebiu** [comment]
This is a [bug](https://bugs.php.net/bug.php?id=55815) in PHP where you can't send files via the PUT method. 
With Laravel what you can do is set the method to POST add a field `_method = PUT` and will work.
https://github.com/laravel/framework/issues/13457

**Comment by mohdabbas** [comment]
I added the field, but it doesn't work. Can you please share an example?
