### ISSUE TITLE
how can upload file with put on update form

### ISSUE THREAD

**Issue by claymore07** [cretueusebiu/vform#56]
I have a form with multipart/form-data and the API for the update with put/patch, I'm using the code below to upload the file but the request on the server side is empty! the inspect shows the data has been sent but the server and laravel update method shows request is empty! how can I solve it?

``` this.form.submit('put', '/api/paper/'+this.paper.id, {
                    // Transform form data to FormData
                    transformRequest: [function (data, headers) {
                        return objectToFormData(data)
                    }]
                }).then(() => {
                   // do some stuff  
                }).catch((e) => {
                    // do some stuff  
                    }
                );
```

**Comment by mohdabbas** [comment]
I am also having the same issue!!! Did you find any fix?

**Comment by dvomaks** [comment]
I want to use method PUT to upload file with Postman. But if I point data to x-www-url-formurlencoded, it would not allow me to use File input. So in this case, with Postman, I use POST, but with a _method input equal to PUT. It will allows me to PUT data with file (This trick only works with Laravel)

Example for axios:
data['_method'] = 'PUT' // or PATH

// Transform form data to FormData
                    transformRequest: [function (data, headers) {
                        return objectToFormData(data)
                    }]
                }).then(() => {
                   // do some stuff  
                }).catch((e) => {
                    // do some stuff  
                    }
                );
