### ISSUE TITLE
Can't get 422 (Unprocessable Entity) errors when use try{}catch(){} in server

### ISSUE THREAD

**Issue by fawel11** [cretueusebiu/vform#57]
When i use 
` try{  }
 catch (ModelNotFoundException $y) {
            return JsonResponse::create(['message' => 'Model Value Not Found'], 410);
        }catch (UnprocessableEntityHttpException $exception) {
            return JsonResponse::create(['message' => $exception->getMessage()], 422);
        }catch (Exception $exception) {
            return JsonResponse::create(['message' =>  $exception->getMessage()], 410);
        }`

then this code is not working:
` <has-error v-if="!form.name" :form="form" field="name"></has-error>`

My question is how i can get errors to show in div below each input ?

**Comment by cretueusebiu** [comment]
The form will only catch 422 validation errors. For anything else you need a try/catch in your JS code.

**Comment by fawel11** [comment]
Solved!
`catch (ValidationException $exception) {
           return JsonResponse::create(['message' => $exception->getMessage(),'errors'=>$exception->validator->getMessageBag()->toArray()],422);
        }`
