### ISSUE TITLE
headers

### ISSUE THREAD

**Issue by wcosmas** [cretueusebiu/vform#59]
How do I attach headers. especially the authorization header

**Comment by cretueusebiu** [comment]
You can use `form.submit(method, url, config = {})` and specify the headers in the config object that will be based to axios.

But for something like Authorization you want to make that global using an axios interceptor, [like this](https://github.com/cretueusebiu/laravel-vue-spa/blob/master/resources/js/plugins/axios.js).

**Comment by wcosmas** [comment]
Thanks a lot bro.
