### ISSUE TITLE
Uncaught TypeError: Cannot call a class as a function

### ISSUE THREAD

**Issue by Wipsly** [cretueusebiu/vform#6]
Hi,

I followed the instructions but I get the following error in my console:

Uncaught TypeError: Cannot call a class as a function

Any idea?

**Comment by cretueusebiu** [comment]
Hmm, can you show me the code you use ?

**Comment by Wipsly** [comment]
In my app.js

`// vForm Plugin
import vForm from 'vform'
Vue.use(vForm)`

And this is in my Test.vue 

`<script>
    export default {
        data() {
            return {
                form: Form({
                    username: null
                })
            }
        },

        methods: {
            login() {
               this.form.post('/api/test')
                       .then(({ data }) => { console.log(data) })
            }
        }
    }
</script>`

**Comment by cretueusebiu** [comment]
Please see the docs https://github.com/cretueusebiu/vform#usage

**Comment by Wipsly** [comment]
If I do it exactly like in the instruction i get.

Form is not defined

**Comment by cretueusebiu** [comment]
Can you show me your code ?

**Comment by Wipsly** [comment]
Hmm... It works when I import directly in my component like so.

Test.vue

```
<script>
    import { Form, HasError, AlertError, AlertSuccess } from 'vform'

    Vue.component('has-error', HasError)
    Vue.component('alert-error', AlertError)
    Vue.component('alert-success', AlertSuccess)

    export default {
        data() {
            return {
                form: new Form({
                    username: null
                })
            }
        },

        methods: {
            login() {
               this.form.post('/api/test')
                       .then(({ data }) => { console.log(data) })
            }
        }
    }
</script>
```

But it would be nice if I could use it globaly in my app.js file

**Comment by cretueusebiu** [comment]
Globally means you want to have it in the `window` scope:

```javascript
import { Form } from 'vform'

window.Form = Form
```

**Comment by cretueusebiu** [comment]
Is that working for you ?

**Comment by ServerJunge** [comment]
Works for me! Thanks!

**Comment by Hayder-M** [comment]
Hi.
I followed the instructions but I get 2 errors in my terminal :
export 'HasError' (imported as 'HasError') was not found in 'vform' (possible exports: Errors, Form, default)

export 'AlertError' (imported as 'AlertError') was not found in 'vform' (possible exports: Errors, Form, default)

Any solution please?

**Comment by cretueusebiu** [comment]
@Hayder-M See https://vform.vercel.app/#components
