### ISSUE TITLE
How I can send token in header as we do in Axios?

### ISSUE THREAD

**Issue by maliksajid** [cretueusebiu/vform#61]
I use the below code to send token with every request:

```
window.axios.defaults.headers.common = {
 'Accept': 'application/json',
 'Content-Type': 'application/json',
 'Access-Control-Allow-Origin': '*',
 'Access-Control-Allow-Headers': '*',
 'Authorization': 'Bearer' + localStorage.getItem('token')
}
```

**Is it possible something like this with vform?**

**Comment by cretueusebiu** [comment]
You can do the same, just make sure to import axios because it's not available in the window.

**Comment by maliksajid** [comment]
Can you show me the sample?

**Comment by cretueusebiu** [comment]
I use an interceptor https://github.com/cretueusebiu/laravel-vue-spa/blob/master/resources/js/plugins/axios.js

**Comment by maliksajid** [comment]
**How I imported Vform in app.js(Parent Component)**

```
// VForm
import { Form, HasError, AlertError } from 'vform'
Vue.component(HasError.name, HasError)
Vue.component(AlertError.name, AlertError)
```


**How I imported axios in  app.js code**
```
import axios from 'axios'
window.axios.defaults.headers.common = {
    'Accept': 'application/json',
    'Content-Type': 'application/json',
    'Access-Control-Allow-Origin': '*',
    'Access-Control-Allow-Headers': '*',
    'Authorization': 'Bearer' + localStorage.getItem('token')
};
```


**This my my get method**

```
// Populate table
    index() {
      this.form.get("api/campus")
        .then(({ data }) => (this.campuses = data));
    },
```

**Comment by cretueusebiu** [comment]
When you do `import axios from 'axios`' just use `axios` not `window.axios`.
See my example https://github.com/cretueusebiu/laravel-vue-spa/blob/master/resources/js/plugins/axios.js

**Comment by maliksajid** [comment]
Thanks for your quick response. Let me to try again.

**Comment by maliksajid** [comment]
Same Issue Not working

**Comment by maliksajid** [comment]
[image: image.png]
[image: image.png]
[image: image.png]
[image: image.png]

**Comment by cretueusebiu** [comment]
You're clearly doing something work. See my Laravel-Vue template it uses both this package and axios with headers and token https://github.com/cretueusebiu/laravel-vue-spa

**Comment by maliksajid** [comment]
> You're clearly doing something wrong. See my Laravel-Vue template it uses both this package and axios with headers and token https://github.com/cretueusebiu/laravel-vue-spa

Thanks bro! Let me to check it
