### ISSUE TITLE
vfrom fill datetime

### ISSUE THREAD

**Issue by nathanwuiske** [cretueusebiu/vform#65]
When using a datetime input, `this.Form.fill(object); ` fails to fill the form at all. Works perfectly fine with date, as soon as changed to datetime it doesn't work.

**Comment by weblikero** [comment]
Hello, 
I'm having almost same issue. When I'm using this.form.fill(object) the datetime input is not filled in the form.
There is some solution on this please?
My DB field is represented like this:
https://ibb.co/PFMXqR7

and on form the date field is not filled:
 https://ibb.co/Cz53gq8
