### ISSUE TITLE
OriginalData not updated when use fill method

### ISSUE THREAD

**Issue by Zooba21** [cretueusebiu/vform#69]
Hi ! 

First of all, thanks for this package ! It saves me lot of time ! 

I noticed that all form objects has en originalData object where are store the initial values on form creation. 
Anyway, when you use the fill method on the form to update it, the originalData are not changed. 

Is there an easy way to update the original Data that way ? 

I am using a form which could be updated several times, and I have to trigger an alert if a specific value is different from the original (the original should here be the last value filled). 

If not, maybe an option on fill method could be added to update the originalData object ? 

Thanks for any advice on this subject !

**Comment by robjuz** [comment]
My solution to this:

`this.form = new Form(this.form.data());`

**Comment by cretueusebiu** [comment]
Added `Form.update`
