### ISSUE TITLE
Axios interceptors not working (Authorization header not being attached)

### ISSUE THREAD

**Issue by chrislandeza** [cretueusebiu/vform#7]
Hi, I don't know if this is the right place to create this issue but anyways, I'm toying around with your [laravel-vue-spa](https://github.com/cretueusebiu/laravel-vue-spa) starter app when I encounter this issue.

The authorization header (on your `util/interceptors.js`) is not being attached if I use this library to perform ajax request (e.g. on. `pages/settings/_profile.vue@update()` method). but if I use axios alone, it works.

I'm trying to re-create your starter app from scratch to get me familiarized with the setup so I did the following

1. Installed Laravel 5.4
2. Installed Laravel Passport for API authentication
3. Installed  NPM Packages that I need (see below):
4. Copied your resources/assets/* files to my resources/assets folder
5. run `npm run dev`

Login and Registration works fine.

package.json
```
"devDependencies": {
    "babel-plugin-transform-async-to-generator": "^6.22.0",
    "babel-plugin-transform-runtime": "^6.23.0",
    "babel-preset-es2015": "^6.24.0",
    "babel-preset-stage-2": "^6.22.0",
    "cross-env": "^3.2.3",
    "laravel-mix": "0.*",
    "svg-sprite-loader": "^0.3.0"
  },
  "dependencies": {
    "axios": "^0.15.3",
    "bootstrap-sass": "^3.3.7",
    "jquery": "^3.2.1",
    "js-cookie": "^2.1.4",
    "lodash": "^4.17.4",
    "sweetalert2": "^6.5.5",
    "tether": "^1.4.0",
    "vform": "^0.7.3",
    "vue": "^2.2.6",
    "vue-meta": "^0.5.5",
    "vue-router": "^2.3.1",
    "vuex": "^2.2.1",
    "vuex-router-sync": "^4.1.2"
  }
```

.babelrc
```
{
    "presets": ["es2015", "stage-2"],
    "plugins": ["transform-runtime", "transform-async-to-generator"]
}
```

**Comment by cretueusebiu** [comment]
Does this happen on  laravel-vue-spa or just in your project ?

**Comment by chrislandeza** [comment]
Just in the project I created from scratch @_@

I've created a test repo [here](https://github.com/chrislandeza/sample-starter-app) to reproduce the problem.

Can't figure out what I missed. I just copied your whole `resources/assets/*` and package.jsonto my mine.

**Comment by cretueusebiu** [comment]
In my implementation I just return a `token` on login. But in your case with Passport, you have 2 different tokens `access_token` and `refresh_token`, but you didn't made any changes to the code to store those tokens and then pass them via the `Authorization` header.

**Comment by chrislandeza** [comment]
Sorry I didn't mention that, I've updated the login.vue and register.vue to use `access_token` property instead of just `token`. as I said, the Login and Registration flow works fine, token was stored properly on the auth store.

**Comment by chrislandeza** [comment]
Anyways, I ended up using my own Form object since I already have one for my personal use.

Thanks for the help @cretueusebiu - I love your projects :+1:

**Comment by cretueusebiu** [comment]
Install the latest version of `vform` (0.7.4) and should be working now. The packaged required axios 0.15.3 and you had a newer version 0.16 and the interceptor was only for your version.
