### ISSUE TITLE
Cant update the value of data

### ISSUE THREAD

**Issue by JohnCarlo29** [cretueusebiu/vform#71]
I have set a component data as shown below:

`data() {
        return {
            form: new Form({
                sender_name: '',
                sender_email: '',
                sender_mobile: '',
            })
        }
    }`

but when I try to update the data of the form in mounted() it doenst change the value of sender_name key:

`mounted() {
        if (this.senderDetails) {
            let senderDetails = JSON.parse(this.senderDetails);
            this.form.sender_name = senderDetails.full_name;
        }
   },`

**Comment by Xoshbin** [comment]
Hi @JohnCarlo29 Could you solve that issue? I have the same issue trying to update a value from mounted() but it's not working. If you could solve it can you share it here please? thank you
