### ISSUE TITLE
TypeError: this.role.put is not a function

### ISSUE THREAD

**Issue by karimakrane** [cretueusebiu/vform#76]
hello 
my problem is that when i call any vform method i have this error :
app.js:2847 Uncaught (in promise) TypeError: this.role.put is not a function
    at VueComponent.saveRole (app.js:2847)

also with TypeError: this.role.post is not a function;
my app.js
import Vue from 'vue'
import Vuetify from 'vuetify'
import es from 'vuetify/es5/locale/es'
import Vuex from 'vuex'
import VueRouter from 'vue-router'
import moment from 'moment'
import swal from 'sweetalert2'
import VeeValidate , { Validator } from 'vee-validate'
import fr from 'vee-validate/dist/locale/fr'
import storeData from  './store'
import {Form} from 'vform'

Vue.use(Vuetify)
Vue.use(Vuex)
Vue.use(VueRouter)
Vue.use(VeeValidate)

Validator.localize('fr', fr);

const store = new Vuex.Store(storeData);
window.Form = Form;
....

then my data component :
 data: () => ({
            role: new Form({}),
            taille:'',
            id:'',
            editer:false,
            texte_titre:'Détails',
            text_boutton:'Editer',
        }),
and finaly my method :
saveRole(){
                this.role.put('/api/roles/'+this.role.id,this.role)
               .then(response=>{
                    if(response.data.message ==='success'){
                        
                    }  
               })
                .catch(e => {
               
                });
            },

**Comment by ricardogobbosouza** [comment]
@karimakrane try:
```js
data() {
  return {
    role: new Form(),
    taille: '',
    id: '',
    editer: false,
    texte_titre: 'Détails',
    text_boutton: 'Editer'
  }
}
```
