### ISSUE TITLE
Option to delay clearing errors until after response is received

### ISSUE THREAD

**Issue by alex-osborn** [cretueusebiu/vform#77]
Great work with the package.

Are you open to including an option to delay clearing the errors until after the response is received? Alternatively, I think that retaining the existing errors until after the response is received is better UX.

Specifically, this would avoid a "flickering" issue, if the user submits the form and the response is received quickly. What is happening is that on submit, any existing form errors disappear, which means the height of the form can jump around if your errors display below the fields.

Examples - see screenshots, the UI jumps from the first screenshot, to the second, then back again.

![Screen Shot 2019-09-07 at 12 38 52 PM](https://user-images.githubusercontent.com/880420/64467424-8801c000-d16c-11e9-9887-2eb0b9977055.png)
![Screen Shot 2019-09-07 at 12 38 45 PM](https://user-images.githubusercontent.com/880420/64467422-86d09300-d16c-11e9-895a-8246e3b50209.png)

**Comment by cretueusebiu** [comment]
You can override the `startProcessing` method instead: 

```javascript
Form.prototype.startProcessing = function () {
  // this.errors.clear()
  this.busy = true
  this.successful = false
}
```
