### ISSUE TITLE
How to configure vform to make form.patch requests work in nuxt.js?

### ISSUE THREAD

**Issue by connecteev** [cretueusebiu/vform#79]
I am using vform in my nuxt projet communicating with Laravel APIs.

Doing the following:
```
      this.form.patch('/settings/update', {
        'userId': this.$auth.user.id,
        'userOriginalUsername': this.$auth.user.username,
        'userOriginalEmail': this.$auth.user.email,
        ...this.form.data(),
      })
```
Makes an API request to http://localhost:/3000/settings/update instead of my configured axios URL:
http://localhost:/8000/api/v1/settings/update

Full code is here:
https://gist.github.com/connecteev/3398097dd741dd49c6561c1c763d89bb#file-account-vue-L94

```

How do you configure vform for axios requests in nuxt.js?

**Comment by cretueusebiu** [comment]
You might be using a custom axios instance.
Try this https://github.com/cretueusebiu/vform/issues/30#issuecomment-412006708

**Comment by connecteev** [comment]
This worked beautifully, thanks for the quick answer Cretu.

This is what I originally put in my vform.js plugin (similar to what you have here):
https://github.com/cretueusebiu/laravel-nuxt/blob/master/client/plugins/vform.js
Why did we have to do this? [#30 (comment)](https://github.com/cretueusebiu/vform/issues/30#issuecomment-412006708)

Btw <has-error> is still not working, even though I removed form.errors = response as you suggested. More in #80
