### ISSUE TITLE
form.errors.has() not recognized

### ISSUE THREAD

**Issue by connecteev** [cretueusebiu/vform#80]
I am using vform in nuxt.js communicating with laravel APIs, and tried to emulate the form code here:
https://github.com/cretueusebiu/laravel-nuxt/blob/master/client/pages/settings/profile.vue

But I keep getting an error:
```
form.errors.has() not recognized.
```

What am I missing? Full code is here:
```
            <input v-model="form.email" :class="{ 'is-invalid': form.errors.has('email') }" name="email" placeholder="Your email" class="kb_form_input form-control" />

```
https://gist.github.com/connecteev/3398097dd741dd49c6561c1c763d89bb#file-account-vue-L24

**Comment by cretueusebiu** [comment]
I think it's because you are setting `form.errors = response` here https://gist.github.com/connecteev/3398097dd741dd49c6561c1c763d89bb#file-account-vue-L123

**Comment by connecteev** [comment]
Thanks for the quick response. 

< has-error > is still not working, even though I removed ```form.errors = response``` as you suggested. The rest of the code is the same as what I posted above.
This is the error I get in the console:

```
[Vue warn]: Unknown custom element: <has-error> - did you register the component correctly? For recursive components, make sure to provide the "name" option.

found in

---> <Pages/settings/account.vue> at pages/settings/account.vue
       <Pages/settings.vue> at pages/settings.vue
         <Nuxt>
           <Default> at layouts/default.vue
             <Root>
```
It seems like something is not being registered correctly.

**Comment by connecteev** [comment]
Also I tried adding to your vform.js plugin, but it didnt help.
```
import Vue from 'vue'
import { HasError, AlertError, AlertSuccess } from 'vform'

Vue.component(HasError.name, HasError)
Vue.component(AlertError.name, AlertError)
Vue.component(AlertSuccess.name, AlertSuccess)

```

**Comment by connecteev** [comment]
@cretueusebiu A tip on how to get has-error working would be helpful.

**Comment by connecteev** [comment]
any thoughts on this would be great

**Comment by Snakzi** [comment]
Have you ever solved this issue? @connecteev
