### ISSUE TITLE
Ability to add more data to the form dynamically

### ISSUE THREAD

**Issue by stevebauman** [cretueusebiu/vform#9]
I was wondering if it's possible to add more data to the form after it's been instantiated?

For example (psuedo code):

```html
<template>
    <select v-model="form.approvers" multiple id="approvers" name="approvers"></select>
</template>

<script>
export default {
    data() {
        return {
            form: new Form({
                approvers: [],
            })
        }
    }

    mounted() {
         $('#approvers').select2({
            placeholder: "Enter approvers ",
        });
    },

    methods: {
        save() {
            // Ex.
            this.form.setData(key, value);

            this.form.post();
        }
    }
}
</script>
```

I have a multi-select form input that is constructed using [Select2](https://select2.github.io/), but using `v-model="form.approvers"` on the select doesn't seem to post the selected values from select2.

Do you know of any ways around this or why it might not be grabbing the values from the select input?

Thanks! :)

**Comment by stevebauman** [comment]
Just some more information, I'm using select2's ajax feature to pull in it's result set dynamically. Upon selection, select2 actually ads the select option to the element automatically, so I'm assuming this dom update isn't seen by Vue?

**Comment by cretueusebiu** [comment]
You can:

```
this.form.my_key = 'value'
```

But for your case you should make a custom component then have something like:

```
<select2 v-model="form.my_key"></select2>
```

https://vuejs.org/v2/examples/select2.html

Or try this one https://github.com/monterail/vue-multiselect

**Comment by stevebauman** [comment]
Ah geese you're a genius! Didn't think that would work.

Works perfectly. Thanks so much for your support and your amazing work here!

**Comment by joneyspark** [comment]
![expect-array](https://user-images.githubusercontent.com/34330722/78502551-82606d00-7783-11ea-888c-b3483a0da764.png)

> **Can anyone help me I used Vform When I clicked edit button then it's show this error that expect array but I used already array in categories[] and also how to selected default category ?**

```
<select class="form-control" 
                     multiple
                     v-model="form.categories"
                     name="categories[]"
                     :class="{ 'is-invalid': form.errors.has('categories') }">
                        <option v-for="catetoryValue in getCategory" :key="catetoryValue.id" :value="catetoryValue.id">{{ catetoryValue.name }}</option>
                    </select>
<has-error :form="form" field="categories"></has-error>
```

```

data() {
    return {
      editMode: false,
      values: {},
      getTag: {},
      categories:[],
      count: "",
      body:"",
      selected: null,
      form: new Form({
        id: "",
        user_id: "",
        title: "",
        image: "",
        body:"",
        categories:[],
        tags:[],
        view_count: "",
        status: "",
        is_approved: "",
      })
    };
  },
```

**Comment by arrcorona** [comment]
> ![expect-array](https://user-images.githubusercontent.com/34330722/78502551-82606d00-7783-11ea-888c-b3483a0da764.png)
> 
> > **Can anyone help me I used Vform When I clicked edit button then it's show this error that expect array but I used already array in categories[] and also how to selected default category ?**
> 
> ```
> <select class="form-control" 
>                      multiple
>                      v-model="form.categories"
>                      name="categories[]"
>                      :class="{ 'is-invalid': form.errors.has('categories') }">
>                         <option v-for="catetoryValue in getCategory" :key="catetoryValue.id" :value="catetoryValue.id">{{ catetoryValue.name }}</option>
>                     </select>
> <has-error :form="form" field="categories"></has-error>
> ```
> 
> ```
> 
> data() {
>     return {
>       editMode: false,
>       values: {},
>       getTag: {},
>       categories:[],
>       count: "",
>       body:"",
>       selected: null,
>       form: new Form({
>         id: "",
>         user_id: "",
>         title: "",
>         image: "",
>         body:"",
>         categories:[],
>         tags:[],
>         view_count: "",
>         status: "",
>         is_approved: "",
>       })
>     };
>   },
> ```


any update on this?

**Comment by arrcorona** [comment]
@joneyspark try this as mentioned above.  https://github.com/shentao/vue-multiselect
