### ISSUE TITLE
working with <select></select> elements

### ISSUE THREAD

**Issue by royacle** [cretueusebiu/vform#96]
Pls I am trying to implement error handling on <select></select> element but I am yet to achieve success. Below is what I have done.
`<div class="form-group">`
 `<label>Category</label>`
   `<select class="form-control" name="categories_id" style="width: 100%;" type="number" 
                               v-model="form.category_id" 
                              :class="{ 'is-invalid': form.errors.has('categories_id') }">
                              <option value="">Select Category</option>
                              <option v-for="(category, c) in categories.data" 
                                v-bind:key="c" :value="category.id">{{category.name}}</option>`
  `</select>`
 `<has-error :form="form" field="categories_id"></has-error>`
`</div>`

I have 2 issues:
1. I get this via the  XHR response on developer bar `{"message": "The given data was invalid.","errors":{"category_id":["The category id field is required."]}}`.
3. The error doesn't get displayed in the <has-error></has-error> element.

Pls how to correct this?

**Comment by mkakpabla** [comment]
Correct the field name 
`:class="{ 'is-invalid': form.errors.has('category_id') }"`
`<has-error :form="form" field="category_id"></has-error>`

**Comment by usmanbasharmal123** [comment]
@royacle I face the same problem did you solve it

**Comment by royacle** [comment]
> Correct the field name
> `:class="{ 'is-invalid': form.errors.has('category_id') }"`
> `<has-error :form="form" field="category_id"></has-error>`

Thanks buddy, got it resolved. You're right, guess some oversight from me.

**Comment by royacle** [comment]
> @royacle I face the same problem did you solve it

Sorry man, haven't been here in ages. So the field name should be same with the error name. If you couldn't figure it out, kindly paste your code here for assistance.
