### ISSUE TITLE
How to send multipart/form-data with image and fields

### ISSUE THREAD

**Issue by zarpio** [cretueusebiu/vform#97]
If anyone has set up this case please share your code.

My form has the following fields
- First Name
- Last Name
- Email
- User Avatar (File)

**Comment by AndreSouzaAbreu** [comment]
I also would like to know how to send files using vform!

**Comment by AndreSouzaAbreu** [comment]
I have found [a solution to your problem on StackOverflow](https://stackoverflow.com/questions/54147039/vue-vform-file-upload) and it has worked for me too! 

The code goes something like that
```
// in vue template
<input type="file" @input="addFile" name="avatar">

// js
        data() {
            return {
                    form: new VueForm({fname: "", lname: "", email: "", avatar: ""})
            }
        }
// in methods
        addUser() {
            this.form.post('users', {transformRequest: [data => objectToFormData(data)]})
                .then(res => window.alert("success"))
                .catch(error => console.log(error))
        },
        addFile() {
             this.form.avatar = window.event.target.files[0]
        }
```

**Comment by Julianvschijndel** [comment]
@AndreSouzaAbreu I tried you're code but that also doesn't work by me.

**Comment by i-defranca** [comment]
> @AndreSouzaAbreu I tried you're code but that also doesn't work by me.

check this example https://github.com/cretueusebiu/vform/blob/master/example/upload.html
instead of getting his cdn script, I just coppied the function to my head and also tested for null fields

**Comment by Julianvschijndel** [comment]
@i-defranca I fixed it already.

**Comment by saadabdurrazaq** [comment]
I get some issue. Help me please https://github.com/cretueusebiu/vform/issues/135
